language: node_js
node_js: 8
script: npm pack

if: tag IS blank

after_success:
  - npm install -g zeus-ci
  - zeus-ci upload -t "application/tar+npm" *.tgz

notifications:
  webhooks:
    urls:
      - https://zeus.ci/hooks/40814526-c583-11e7-8bb8-0a580a280746/public/provider/travis/webhook
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
